import type { Metadata } from "next";
import "./globals.css";
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <p>🎞️나와 맞는 영화 캐릭터</p>
          </header>
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  );
}
